# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170403_1641'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Departamento'),
        ),
    ]
