# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_programa_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
