# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20170505_1639'),
        ('presupuesto', '0003_programa_cuenta_bancaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='pp',
        ),
        migrations.AddField(
            model_name='programa',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Banco'),
        ),
    ]
