# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_partida_monto_1t_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='monto_1t_amplicacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_1t_ejercido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_1t_modificado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_1t_por_ejercer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_1t_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
