# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_auto_20170510_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='monto_1t_amplicacion',
            new_name='monto_1t_ampliacion',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='monto_2t_amplicacion',
            new_name='monto_2t_ampliacion',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='monto_3t_amplicacion',
            new_name='monto_3t_ampliacion',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='monto_4t_amplicacion',
            new_name='monto_4t_ampliacion',
        ),
    ]
