# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170228_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Arq.', 'Arq̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣̣.'), ('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
