# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170307_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).'), ('Arq.', 'Arq.'), ('Tec.', 'Tec.')], default='C.', max_length=30),
        ),
    ]
