# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170403_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Arq.', 'Arq.'), ('Tec.', 'Tec.'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.')], default='C.', max_length=30),
        ),
    ]
