# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170403_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.'), ('Tec.', 'Tec.')], default='C.', max_length=30),
        ),
    ]
