# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170404_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Arq.', 'Arq.'), ('Tec.', 'Tec.'), ('Ing.', 'Ing.')], default='C.', max_length=30),
        ),
    ]
