# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170404_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Arq.', 'Arq.')], default='C.', max_length=30),
        ),
    ]
