# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170405_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('Arq.', 'Arq.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
