# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20170405_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Arq.', 'Arq.'), ('Dr.', 'Dr.'), ('Tec.', 'Tec.')], default='C.', max_length=30),
        ),
    ]
