# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20170405_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('Arq.', 'Arq.')], default='C.', max_length=30),
        ),
    ]
