# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170405_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.')], default='C.', max_length=30),
        ),
    ]
