# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20170405_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFC', models.FileField(upload_to='Expedientes/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Arq.', 'Arq.'), ('Tec.', 'Tec.'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Perfil'),
        ),
    ]
