# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20170406_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='Perfil',
            new_name='perfil',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
