# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20170406_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Arq.', 'Arq.'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
    ]
