# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170406_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='IFE',
            field=models.ImageField(blank=True, null=True, upload_to='IFE/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='RFC',
            field=models.FileField(blank=True, null=True, upload_to='Expedientes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Arq.', 'Arq.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.')], default='C.', max_length=30),
        ),
    ]
