# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20170406_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Moral', 'P. Moral'), ('P. Física', 'P. Física')], default='P. Física', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
    ]
