# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20170410_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='IFE',
            field=models.ImageField(upload_to='IFE/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='RFC',
            field=models.ImageField(upload_to='RFC/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Moral', 'P. Moral'), ('P. Física', 'P. Física')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Tec.', 'Tec.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
