# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20170410_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Arq.', 'Arq.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
    ]
