# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20170410_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P. Moral', 'P. Moral'), ('P. Física', 'P. Física')], max_length=20)),
                ('RFC', models.ImageField(upload_to='RFC/%Y/%m/%d/')),
                ('IFE', models.ImageField(upload_to='IFE/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Tec.', 'Tec.'), ('Arq.', 'Arq.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).')], default='C.', max_length=30),
        ),
        migrations.AddField(
            model_name='expediente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Perfil'),
        ),
    ]
