# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20170410_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='RFC',
            field=models.ImageField(blank=True, null=True, upload_to='RFC/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.'), ('Arq.', 'Arq.'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.')], default='C.', max_length=30),
        ),
    ]
