# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20170412_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='accounts.Perfil'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Física', 'P. Física'), ('P. Moral', 'P. Moral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('Tec.', 'Tec.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).'), ('Arq.', 'Arq.')], default='C.', max_length=30),
        ),
    ]
