# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20170412_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('Arq.', 'Arq.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
    ]
