# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20170412_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Arq.', 'Arq.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
