# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20170412_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='IFE',
            field=models.FileField(upload_to='IFE/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='RFC',
            field=models.FileField(upload_to='RFC/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('Tec.', 'Tec.'), ('T. S. U.', 'T. S. U.'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
    ]
