# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20170417_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='IFE',
            field=models.FileField(blank=True, null=True, upload_to='IFE/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='RFC',
            field=models.FileField(blank=True, null=True, upload_to='RFC/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='accounts.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Arq.', 'Arq.'), ('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).')], default='C.', max_length=30),
        ),
    ]
