# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20170417_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.'), ('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Arq.', 'Arq.')], default='C.', max_length=30),
        ),
    ]
