# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20170427_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='IFE',
            new_name='Identifación_oficial',
        ),
        migrations.AddField(
            model_name='expediente',
            name='Acta_constitutiva',
            field=models.FileField(blank=True, null=True, upload_to='Acta/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Comprobante_de_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='Comprobante/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Opinión_de_cumplimiento',
            field=models.FileField(blank=True, null=True, upload_to='Opinon de cumplimiento/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Registro_de_padrón_de_proveedores',
            field=models.FileField(blank=True, null=True, upload_to='Registro de padron/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Representación_legal',
            field=models.FileField(blank=True, null=True, upload_to='Representacion_legal/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Tres_cotizaciones',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Física', 'P. Física'), ('P. Moral', 'P. Moral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Arq.', 'Arq.'), ('Tec.', 'Tec.')], default='C.', max_length=30),
        ),
    ]
