# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20170502_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Moral', 'P. Moral'), ('P. Física', 'P. Física')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Arq.', 'Arq.'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
    ]
