# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20170502_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Física', 'P. Física'), ('P. Moral', 'P. Moral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Arq.', 'Arq.'), ('Tec.', 'Tec.'), ('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.')], default='C.', max_length=30),
        ),
    ]
