# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20170503_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('Arq.', 'Arq.'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Tec.', 'Tec.'), ('Mtro(a).', 'Mtro(a).')], default='C.', max_length=30),
        ),
    ]
