# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20170505_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Arq.', 'Arq.'), ('Ing.', 'Ing.'), ('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.')], default='C.', max_length=30),
        ),
    ]
