# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20170510_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Arq.', 'Arq.'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).')], default='C.', max_length=30),
        ),
    ]
