# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_auto_20170512_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Arq.', 'Arq.'), ('Ing.', 'Ing.'), ('Tec.', 'Tec.'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
