# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_auto_20170512_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('P. Física', 'P. Física'), ('P. Moral', 'P. Moral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Arq.', 'Arq.'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
