# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecursoFinanciero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10)),
                ('concepto', models.CharField(max_length=100)),
                ('importe_numero', models.DecimalField(decimal_places=2, max_digits=20)),
                ('importe_letra', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA'), ('CHEQUE', 'CHEQUE')], max_length=30)),
                ('clabe', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('a_nombre_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_nombre_de', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['folio'],
            },
        ),
    ]
