# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_auto_20170228_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='a_nombre_de',
            field=models.CharField(max_length=50),
        ),
    ]
