# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20170228_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='a_nombre_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_nombre_de', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA')], max_length=30),
        ),
    ]
