# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_auto_20170228_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrecursofinanciero',
            options={'ordering': ['creacion']},
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA'), ('CHEQUE', 'CHEQUE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
