# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_auto_20170405_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecursofinanciero',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='solicitudrecursofinanciero',
            name='programa',
        ),
    ]
