# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_auto_20170405_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
