# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_auto_20170405_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprobantes',
        ),
    ]
