# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_auto_20170405_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprobantes',
            new_name='Comprobante',
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA'), ('CHEQUE', 'CHEQUE')], max_length=30),
        ),
    ]
