# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0026_auto_20170412_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='srf',
        ),
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='comprobantes',
            field=models.FileField(blank=True, null=True, upload_to='Comprobantes/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
