# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0030_auto_20170417_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='fecha_pagado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA')], max_length=30),
        ),
    ]
