# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_programa_cuenta_bancaria'),
        ('solicitudes', '0032_auto_20170427_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap', to='presupuesto.Capitulo'),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA')], max_length=30),
        ),
    ]
