# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_programa_cuenta_bancaria'),
        ('solicitudes', '0033_auto_20170502_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecursofinanciero',
            name='cap',
        ),
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='capitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capitulo', to='presupuesto.Capitulo'),
        ),
    ]
