# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0034_auto_20170502_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecursofinanciero',
            name='capitulo',
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA'), ('CHEQUE', 'CHEQUE')], max_length=30),
        ),
    ]
