# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0035_auto_20170502_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecursofinanciero',
            name='programa',
        ),
    ]
