# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_programa_cuenta_bancaria'),
        ('solicitudes', '0036_remove_solicitudrecursofinanciero_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='mes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meses', to='presupuesto.Mes'),
        ),
    ]
