# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0037_solicitudrecursofinanciero_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='cuenta_bancaria_del_programa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
